### ISSUE TITLE
Accessing non-existent property 'WindowStream' of module exports inside circular dependency

### ISSUE THREAD

**Issue by maxharlow** [signicode/scramjet#85]
I get this warning message every time Scramjet is imported? Seems to run ok however.

To reproduce..

`test.js`:
```
const Scramjet = require('scramjet')
```

```
$ node --trace-warnings test
```
```
(node:21638) Warning: Accessing non-existent property 'WindowStream' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.<anonymous> (/Users/max/test/node_modules/scramjet/lib/data-stream.js:1:72)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/max/test/node_modules/scramjet/lib/index.js:15:17)
```

I'm using Scramjet v4.30.2 with Node v14.3.0 on MacOS v10.14.6.

**Comment by MichalCz** [comment]
Yes, the circular dependency is for purpose there and taken into account, but I guess, since new `mjs` modules work in a different way this won't be necessary.

I've taken some time off now to try to push for Scramjet v5.0.0 again so this will be solved also there, but for now, we need to park it unless you have some ideas (PR welcome).

**Comment by MichalCz** [comment]
I'll be solving this in Scramjet v5.0

**Comment by MichalCz** [comment]
Nope, patch underway after all... :)

**Comment by MichalCz** [comment]
@maxharlow `v4.34.5` should solve the issue.

**Comment by maxharlow** [comment]
@MichalCz That works great, thank you
